// flagData.js — paste this file into your project manually, do not ask Claude Code to generate it
// 370 flags from hatscripts circle-flags library

export const FLAGS = [
  { code: "ad", name: "Andorra", url: `https://hatscripts.github.io/circle-flags/flags/ad.svg` },
  { code: "ae", name: "United Arab Emirates", url: `https://hatscripts.github.io/circle-flags/flags/ae.svg` },
  { code: "af", name: "Afghanistan", url: `https://hatscripts.github.io/circle-flags/flags/af.svg` },
  { code: "ag", name: "Antigua and Barbuda", url: `https://hatscripts.github.io/circle-flags/flags/ag.svg` },
  { code: "ai", name: "Anguilla", url: `https://hatscripts.github.io/circle-flags/flags/ai.svg` },
  { code: "al", name: "Albania", url: `https://hatscripts.github.io/circle-flags/flags/al.svg` },
  { code: "am", name: "Armenia", url: `https://hatscripts.github.io/circle-flags/flags/am.svg` },
  { code: "an", name: "Netherlands Antilles", url: `https://hatscripts.github.io/circle-flags/flags/an.svg` },
  { code: "ao", name: "Angola", url: `https://hatscripts.github.io/circle-flags/flags/ao.svg` },
  { code: "aq", name: "Antarctica", url: `https://hatscripts.github.io/circle-flags/flags/aq.svg` },
  { code: "ar", name: "Argentina", url: `https://hatscripts.github.io/circle-flags/flags/ar.svg` },
  { code: "as", name: "American Samoa", url: `https://hatscripts.github.io/circle-flags/flags/as.svg` },
  { code: "at", name: "Austria", url: `https://hatscripts.github.io/circle-flags/flags/at.svg` },
  { code: "au", name: "Australia", url: `https://hatscripts.github.io/circle-flags/flags/au.svg` },
  { code: "au-act", name: "Australian Capital Territory", url: `https://hatscripts.github.io/circle-flags/flags/au-act.svg` },
  { code: "au-nsw", name: "New South Wales", url: `https://hatscripts.github.io/circle-flags/flags/au-nsw.svg` },
  { code: "au-nt", name: "Northern Territory", url: `https://hatscripts.github.io/circle-flags/flags/au-nt.svg` },
  { code: "au-qld", name: "Queensland", url: `https://hatscripts.github.io/circle-flags/flags/au-qld.svg` },
  { code: "au-sa", name: "South Australia", url: `https://hatscripts.github.io/circle-flags/flags/au-sa.svg` },
  { code: "au-tas", name: "Tasmania", url: `https://hatscripts.github.io/circle-flags/flags/au-tas.svg` },
  { code: "au-vic", name: "Victoria", url: `https://hatscripts.github.io/circle-flags/flags/au-vic.svg` },
  { code: "au-wa", name: "Western Australia", url: `https://hatscripts.github.io/circle-flags/flags/au-wa.svg` },
  { code: "aw", name: "Aruba", url: `https://hatscripts.github.io/circle-flags/flags/aw.svg` },
  { code: "ax", name: "Åland Islands", url: `https://hatscripts.github.io/circle-flags/flags/ax.svg` },
  { code: "az", name: "Azerbaijan", url: `https://hatscripts.github.io/circle-flags/flags/az.svg` },
  { code: "ba", name: "Bosnia and Herzegovina", url: `https://hatscripts.github.io/circle-flags/flags/ba.svg` },
  { code: "bb", name: "Barbados", url: `https://hatscripts.github.io/circle-flags/flags/bb.svg` },
  { code: "bd", name: "Bangladesh", url: `https://hatscripts.github.io/circle-flags/flags/bd.svg` },
  { code: "be", name: "Belgium", url: `https://hatscripts.github.io/circle-flags/flags/be.svg` },
  { code: "bf", name: "Burkina Faso", url: `https://hatscripts.github.io/circle-flags/flags/bf.svg` },
  { code: "bg", name: "Bulgaria", url: `https://hatscripts.github.io/circle-flags/flags/bg.svg` },
  { code: "bh", name: "Bahrain", url: `https://hatscripts.github.io/circle-flags/flags/bh.svg` },
  { code: "bi", name: "Burundi", url: `https://hatscripts.github.io/circle-flags/flags/bi.svg` },
  { code: "bj", name: "Benin", url: `https://hatscripts.github.io/circle-flags/flags/bj.svg` },
  { code: "bl", name: "Saint Barthélemy", url: `https://hatscripts.github.io/circle-flags/flags/bl.svg` },
  { code: "bm", name: "Bermuda", url: `https://hatscripts.github.io/circle-flags/flags/bm.svg` },
  { code: "bn", name: "Brunei", url: `https://hatscripts.github.io/circle-flags/flags/bn.svg` },
  { code: "bo", name: "Bolivia", url: `https://hatscripts.github.io/circle-flags/flags/bo.svg` },
  { code: "bq-bo", name: "Bonaire", url: `https://hatscripts.github.io/circle-flags/flags/bq-bo.svg` },
  { code: "bq-sa", name: "Saba", url: `https://hatscripts.github.io/circle-flags/flags/bq-sa.svg` },
  { code: "bq-se", name: "Sint Eustatius", url: `https://hatscripts.github.io/circle-flags/flags/bq-se.svg` },
  { code: "br", name: "Brazil", url: `https://hatscripts.github.io/circle-flags/flags/br.svg` },
  { code: "bs", name: "Bahamas", url: `https://hatscripts.github.io/circle-flags/flags/bs.svg` },
  { code: "bt", name: "Bhutan", url: `https://hatscripts.github.io/circle-flags/flags/bt.svg` },
  { code: "bv", name: "Bouvet Island", url: `https://hatscripts.github.io/circle-flags/flags/bv.svg` },
  { code: "bw", name: "Botswana", url: `https://hatscripts.github.io/circle-flags/flags/bw.svg` },
  { code: "by", name: "Belarus", url: `https://hatscripts.github.io/circle-flags/flags/by.svg` },
  { code: "bz", name: "Belize", url: `https://hatscripts.github.io/circle-flags/flags/bz.svg` },
  { code: "ca", name: "Canada", url: `https://hatscripts.github.io/circle-flags/flags/ca.svg` },
  { code: "ca-bc", name: "British Columbia", url: `https://hatscripts.github.io/circle-flags/flags/ca-bc.svg` },
  { code: "ca-qc", name: "Quebec", url: `https://hatscripts.github.io/circle-flags/flags/ca-qc.svg` },
  { code: "cc", name: "Cocos Islands", url: `https://hatscripts.github.io/circle-flags/flags/cc.svg` },
  { code: "cd", name: "Congo DR", url: `https://hatscripts.github.io/circle-flags/flags/cd.svg` },
  { code: "cf", name: "Central African Republic", url: `https://hatscripts.github.io/circle-flags/flags/cf.svg` },
  { code: "cg", name: "Congo", url: `https://hatscripts.github.io/circle-flags/flags/cg.svg` },
  { code: "ch", name: "Switzerland", url: `https://hatscripts.github.io/circle-flags/flags/ch.svg` },
  { code: "ch-gr", name: "Grisons", url: `https://hatscripts.github.io/circle-flags/flags/ch-gr.svg` },
  { code: "ci", name: "Ivory Coast", url: `https://hatscripts.github.io/circle-flags/flags/ci.svg` },
  { code: "ck", name: "Cook Islands", url: `https://hatscripts.github.io/circle-flags/flags/ck.svg` },
  { code: "cl", name: "Chile", url: `https://hatscripts.github.io/circle-flags/flags/cl.svg` },
  { code: "cm", name: "Cameroon", url: `https://hatscripts.github.io/circle-flags/flags/cm.svg` },
  { code: "cn", name: "China", url: `https://hatscripts.github.io/circle-flags/flags/cn.svg` },
  { code: "cn-xj", name: "Xinjiang", url: `https://hatscripts.github.io/circle-flags/flags/cn-xj.svg` },
  { code: "cn-xz", name: "Tibet", url: `https://hatscripts.github.io/circle-flags/flags/cn-xz.svg` },
  { code: "co", name: "Colombia", url: `https://hatscripts.github.io/circle-flags/flags/co.svg` },
  { code: "cq", name: "Sark", url: `https://hatscripts.github.io/circle-flags/flags/cq.svg` },
  { code: "cr", name: "Costa Rica", url: `https://hatscripts.github.io/circle-flags/flags/cr.svg` },
  { code: "cu", name: "Cuba", url: `https://hatscripts.github.io/circle-flags/flags/cu.svg` },
  { code: "cv", name: "Cabo Verde", url: `https://hatscripts.github.io/circle-flags/flags/cv.svg` },
  { code: "cw", name: "Curaçao", url: `https://hatscripts.github.io/circle-flags/flags/cw.svg` },
  { code: "cx", name: "Christmas Island", url: `https://hatscripts.github.io/circle-flags/flags/cx.svg` },
  { code: "cy", name: "Cyprus", url: `https://hatscripts.github.io/circle-flags/flags/cy.svg` },
  { code: "cz", name: "Czechia", url: `https://hatscripts.github.io/circle-flags/flags/cz.svg` },
  { code: "de", name: "Germany", url: `https://hatscripts.github.io/circle-flags/flags/de.svg` },
  { code: "dj", name: "Djibouti", url: `https://hatscripts.github.io/circle-flags/flags/dj.svg` },
  { code: "dk", name: "Denmark", url: `https://hatscripts.github.io/circle-flags/flags/dk.svg` },
  { code: "dm", name: "Dominica", url: `https://hatscripts.github.io/circle-flags/flags/dm.svg` },
  { code: "do", name: "Dominican Republic", url: `https://hatscripts.github.io/circle-flags/flags/do.svg` },
  { code: "dz", name: "Algeria", url: `https://hatscripts.github.io/circle-flags/flags/dz.svg` },
  { code: "ec", name: "Ecuador", url: `https://hatscripts.github.io/circle-flags/flags/ec.svg` },
  { code: "ec-w", name: "Galápagos", url: `https://hatscripts.github.io/circle-flags/flags/ec-w.svg` },
  { code: "ee", name: "Estonia", url: `https://hatscripts.github.io/circle-flags/flags/ee.svg` },
  { code: "eg", name: "Egypt", url: `https://hatscripts.github.io/circle-flags/flags/eg.svg` },
  { code: "eh", name: "Western Sahara", url: `https://hatscripts.github.io/circle-flags/flags/eh.svg` },
  { code: "er", name: "Eritrea", url: `https://hatscripts.github.io/circle-flags/flags/er.svg` },
  { code: "es", name: "Spain", url: `https://hatscripts.github.io/circle-flags/flags/es.svg` },
  { code: "es-ar", name: "Aragon", url: `https://hatscripts.github.io/circle-flags/flags/es-ar.svg` },
  { code: "es-ce", name: "Ceuta", url: `https://hatscripts.github.io/circle-flags/flags/es-ce.svg` },
  { code: "es-cn", name: "Canary Islands", url: `https://hatscripts.github.io/circle-flags/flags/es-cn.svg` },
  { code: "es-ct", name: "Catalonia", url: `https://hatscripts.github.io/circle-flags/flags/es-ct.svg` },
  { code: "es-ga", name: "Galicia", url: `https://hatscripts.github.io/circle-flags/flags/es-ga.svg` },
  { code: "es-ib", name: "Balearic Islands", url: `https://hatscripts.github.io/circle-flags/flags/es-ib.svg` },
  { code: "es-ml", name: "Melilla", url: `https://hatscripts.github.io/circle-flags/flags/es-ml.svg` },
  { code: "es-pv", name: "Basque Country", url: `https://hatscripts.github.io/circle-flags/flags/es-pv.svg` },
  { code: "es-vc", name: "Valencia", url: `https://hatscripts.github.io/circle-flags/flags/es-vc.svg` },
  { code: "et", name: "Ethiopia", url: `https://hatscripts.github.io/circle-flags/flags/et.svg` },
  { code: "et-af", name: "Afar", url: `https://hatscripts.github.io/circle-flags/flags/et-af.svg` },
  { code: "et-am", name: "Amhara", url: `https://hatscripts.github.io/circle-flags/flags/et-am.svg` },
  { code: "et-be", name: "Benishangul-Gumuz", url: `https://hatscripts.github.io/circle-flags/flags/et-be.svg` },
  { code: "et-ga", name: "Gambela", url: `https://hatscripts.github.io/circle-flags/flags/et-ga.svg` },
  { code: "et-ha", name: "Harari", url: `https://hatscripts.github.io/circle-flags/flags/et-ha.svg` },
  { code: "et-or", name: "Oromia", url: `https://hatscripts.github.io/circle-flags/flags/et-or.svg` },
  { code: "et-si", name: "Sidama", url: `https://hatscripts.github.io/circle-flags/flags/et-si.svg` },
  { code: "et-sn", name: "Southern Nations", url: `https://hatscripts.github.io/circle-flags/flags/et-sn.svg` },
  { code: "et-so", name: "Somali", url: `https://hatscripts.github.io/circle-flags/flags/et-so.svg` },
  { code: "et-sw", name: "South West Region", url: `https://hatscripts.github.io/circle-flags/flags/et-sw.svg` },
  { code: "et-ti", name: "Tigray", url: `https://hatscripts.github.io/circle-flags/flags/et-ti.svg` },
  { code: "eu", name: "European Union", url: `https://hatscripts.github.io/circle-flags/flags/eu.svg` },
  { code: "fi", name: "Finland", url: `https://hatscripts.github.io/circle-flags/flags/fi.svg` },
  { code: "fj", name: "Fiji", url: `https://hatscripts.github.io/circle-flags/flags/fj.svg` },
  { code: "fk", name: "Falkland Islands", url: `https://hatscripts.github.io/circle-flags/flags/fk.svg` },
  { code: "fm", name: "Micronesia", url: `https://hatscripts.github.io/circle-flags/flags/fm.svg` },
  { code: "fo", name: "Faroe Islands", url: `https://hatscripts.github.io/circle-flags/flags/fo.svg` },
  { code: "fr", name: "France", url: `https://hatscripts.github.io/circle-flags/flags/fr.svg` },
  { code: "fr-20r", name: "Corsica", url: `https://hatscripts.github.io/circle-flags/flags/fr-20r.svg` },
  { code: "fr-bre", name: "Brittany", url: `https://hatscripts.github.io/circle-flags/flags/fr-bre.svg` },
  { code: "fr-cp", name: "Clipperton Island", url: `https://hatscripts.github.io/circle-flags/flags/fr-cp.svg` },
  { code: "ga", name: "Gabon", url: `https://hatscripts.github.io/circle-flags/flags/ga.svg` },
  { code: "gb", name: "United Kingdom", url: `https://hatscripts.github.io/circle-flags/flags/gb.svg` },
  { code: "gb-con", name: "Cornwall", url: `https://hatscripts.github.io/circle-flags/flags/gb-con.svg` },
  { code: "gb-eng", name: "England", url: `https://hatscripts.github.io/circle-flags/flags/gb-eng.svg` },
  { code: "gb-nir", name: "Northern Ireland", url: `https://hatscripts.github.io/circle-flags/flags/gb-nir.svg` },
  { code: "gb-ork", name: "Orkney", url: `https://hatscripts.github.io/circle-flags/flags/gb-ork.svg` },
  { code: "gb-sct", name: "Scotland", url: `https://hatscripts.github.io/circle-flags/flags/gb-sct.svg` },
  { code: "gb-wls", name: "Wales", url: `https://hatscripts.github.io/circle-flags/flags/gb-wls.svg` },
  { code: "gd", name: "Grenada", url: `https://hatscripts.github.io/circle-flags/flags/gd.svg` },
  { code: "ge", name: "Georgia", url: `https://hatscripts.github.io/circle-flags/flags/ge.svg` },
  { code: "ge-ab", name: "Abkhazia", url: `https://hatscripts.github.io/circle-flags/flags/ge-ab.svg` },
  { code: "gf", name: "French Guiana", url: `https://hatscripts.github.io/circle-flags/flags/gf.svg` },
  { code: "gg", name: "Guernsey", url: `https://hatscripts.github.io/circle-flags/flags/gg.svg` },
  { code: "gh", name: "Ghana", url: `https://hatscripts.github.io/circle-flags/flags/gh.svg` },
  { code: "gi", name: "Gibraltar", url: `https://hatscripts.github.io/circle-flags/flags/gi.svg` },
  { code: "gl", name: "Greenland", url: `https://hatscripts.github.io/circle-flags/flags/gl.svg` },
  { code: "gm", name: "Gambia", url: `https://hatscripts.github.io/circle-flags/flags/gm.svg` },
  { code: "gn", name: "Guinea", url: `https://hatscripts.github.io/circle-flags/flags/gn.svg` },
  { code: "gp", name: "Guadeloupe", url: `https://hatscripts.github.io/circle-flags/flags/gp.svg` },
  { code: "gq", name: "Equatorial Guinea", url: `https://hatscripts.github.io/circle-flags/flags/gq.svg` },
  { code: "gr", name: "Greece", url: `https://hatscripts.github.io/circle-flags/flags/gr.svg` },
  { code: "gs", name: "South Georgia", url: `https://hatscripts.github.io/circle-flags/flags/gs.svg` },
  { code: "gt", name: "Guatemala", url: `https://hatscripts.github.io/circle-flags/flags/gt.svg` },
  { code: "gu", name: "Guam", url: `https://hatscripts.github.io/circle-flags/flags/gu.svg` },
  { code: "gw", name: "Guinea-Bissau", url: `https://hatscripts.github.io/circle-flags/flags/gw.svg` },
  { code: "gy", name: "Guyana", url: `https://hatscripts.github.io/circle-flags/flags/gy.svg` },
  { code: "hk", name: "Hong Kong", url: `https://hatscripts.github.io/circle-flags/flags/hk.svg` },
  { code: "hm", name: "Heard Island", url: `https://hatscripts.github.io/circle-flags/flags/hm.svg` },
  { code: "hn", name: "Honduras", url: `https://hatscripts.github.io/circle-flags/flags/hn.svg` },
  { code: "hr", name: "Croatia", url: `https://hatscripts.github.io/circle-flags/flags/hr.svg` },
  { code: "ht", name: "Haiti", url: `https://hatscripts.github.io/circle-flags/flags/ht.svg` },
  { code: "hu", name: "Hungary", url: `https://hatscripts.github.io/circle-flags/flags/hu.svg` },
  { code: "id", name: "Indonesia", url: `https://hatscripts.github.io/circle-flags/flags/id.svg` },
  { code: "id-jb", name: "West Java", url: `https://hatscripts.github.io/circle-flags/flags/id-jb.svg` },
  { code: "id-jt", name: "Central Java", url: `https://hatscripts.github.io/circle-flags/flags/id-jt.svg` },
  { code: "ie", name: "Ireland", url: `https://hatscripts.github.io/circle-flags/flags/ie.svg` },
  { code: "il", name: "Israel", url: `https://hatscripts.github.io/circle-flags/flags/il.svg` },
  { code: "im", name: "Isle of Man", url: `https://hatscripts.github.io/circle-flags/flags/im.svg` },
  { code: "in", name: "India", url: `https://hatscripts.github.io/circle-flags/flags/in.svg` },
  { code: "in-as", name: "Assam", url: `https://hatscripts.github.io/circle-flags/flags/in-as.svg` },
  { code: "in-gj", name: "Gujarat", url: `https://hatscripts.github.io/circle-flags/flags/in-gj.svg` },
  { code: "in-ka", name: "Karnataka", url: `https://hatscripts.github.io/circle-flags/flags/in-ka.svg` },
  { code: "in-mn", name: "Manipur", url: `https://hatscripts.github.io/circle-flags/flags/in-mn.svg` },
  { code: "in-mz", name: "Mizoram", url: `https://hatscripts.github.io/circle-flags/flags/in-mz.svg` },
  { code: "in-or", name: "Odisha", url: `https://hatscripts.github.io/circle-flags/flags/in-or.svg` },
  { code: "in-tg", name: "Telangana", url: `https://hatscripts.github.io/circle-flags/flags/in-tg.svg` },
  { code: "in-tn", name: "Tamil Nadu", url: `https://hatscripts.github.io/circle-flags/flags/in-tn.svg` },
  { code: "io", name: "British Indian Ocean Territory", url: `https://hatscripts.github.io/circle-flags/flags/io.svg` },
  { code: "iq", name: "Iraq", url: `https://hatscripts.github.io/circle-flags/flags/iq.svg` },
  { code: "iq-kr", name: "Kurdistan", url: `https://hatscripts.github.io/circle-flags/flags/iq-kr.svg` },
  { code: "ir", name: "Iran", url: `https://hatscripts.github.io/circle-flags/flags/ir.svg` },
  { code: "is", name: "Iceland", url: `https://hatscripts.github.io/circle-flags/flags/is.svg` },
  { code: "it", name: "Italy", url: `https://hatscripts.github.io/circle-flags/flags/it.svg` },
  { code: "it-21", name: "Piedmont", url: `https://hatscripts.github.io/circle-flags/flags/it-21.svg` },
  { code: "it-23", name: "Aosta Valley", url: `https://hatscripts.github.io/circle-flags/flags/it-23.svg` },
  { code: "it-25", name: "Lombardy", url: `https://hatscripts.github.io/circle-flags/flags/it-25.svg` },
  { code: "it-32", name: "Trentino-Alto Adige", url: `https://hatscripts.github.io/circle-flags/flags/it-32.svg` },
  { code: "it-34", name: "Veneto", url: `https://hatscripts.github.io/circle-flags/flags/it-34.svg` },
  { code: "it-36", name: "Friuli Venezia Giulia", url: `https://hatscripts.github.io/circle-flags/flags/it-36.svg` },
  { code: "it-42", name: "Liguria", url: `https://hatscripts.github.io/circle-flags/flags/it-42.svg` },
  { code: "it-45", name: "Emilia-Romagna", url: `https://hatscripts.github.io/circle-flags/flags/it-45.svg` },
  { code: "it-52", name: "Tuscany", url: `https://hatscripts.github.io/circle-flags/flags/it-52.svg` },
  { code: "it-55", name: "Umbria", url: `https://hatscripts.github.io/circle-flags/flags/it-55.svg` },
  { code: "it-57", name: "Marche", url: `https://hatscripts.github.io/circle-flags/flags/it-57.svg` },
  { code: "it-62", name: "Lazio", url: `https://hatscripts.github.io/circle-flags/flags/it-62.svg` },
  { code: "it-65", name: "Abruzzo", url: `https://hatscripts.github.io/circle-flags/flags/it-65.svg` },
  { code: "it-67", name: "Molise", url: `https://hatscripts.github.io/circle-flags/flags/it-67.svg` },
  { code: "it-72", name: "Campania", url: `https://hatscripts.github.io/circle-flags/flags/it-72.svg` },
  { code: "it-75", name: "Apulia", url: `https://hatscripts.github.io/circle-flags/flags/it-75.svg` },
  { code: "it-77", name: "Basilicata", url: `https://hatscripts.github.io/circle-flags/flags/it-77.svg` },
  { code: "it-78", name: "Calabria", url: `https://hatscripts.github.io/circle-flags/flags/it-78.svg` },
  { code: "it-82", name: "Sicily", url: `https://hatscripts.github.io/circle-flags/flags/it-82.svg` },
  { code: "it-88", name: "Sardinia", url: `https://hatscripts.github.io/circle-flags/flags/it-88.svg` },
  { code: "je", name: "Jersey", url: `https://hatscripts.github.io/circle-flags/flags/je.svg` },
  { code: "jm", name: "Jamaica", url: `https://hatscripts.github.io/circle-flags/flags/jm.svg` },
  { code: "jo", name: "Jordan", url: `https://hatscripts.github.io/circle-flags/flags/jo.svg` },
  { code: "jp", name: "Japan", url: `https://hatscripts.github.io/circle-flags/flags/jp.svg` },
  { code: "ke", name: "Kenya", url: `https://hatscripts.github.io/circle-flags/flags/ke.svg` },
  { code: "kg", name: "Kyrgyzstan", url: `https://hatscripts.github.io/circle-flags/flags/kg.svg` },
  { code: "kh", name: "Cambodia", url: `https://hatscripts.github.io/circle-flags/flags/kh.svg` },
  { code: "ki", name: "Kiribati", url: `https://hatscripts.github.io/circle-flags/flags/ki.svg` },
  { code: "km", name: "Comoros", url: `https://hatscripts.github.io/circle-flags/flags/km.svg` },
  { code: "kn", name: "Saint Kitts and Nevis", url: `https://hatscripts.github.io/circle-flags/flags/kn.svg` },
  { code: "kp", name: "North Korea", url: `https://hatscripts.github.io/circle-flags/flags/kp.svg` },
  { code: "kr", name: "South Korea", url: `https://hatscripts.github.io/circle-flags/flags/kr.svg` },
  { code: "kw", name: "Kuwait", url: `https://hatscripts.github.io/circle-flags/flags/kw.svg` },
  { code: "ky", name: "Cayman Islands", url: `https://hatscripts.github.io/circle-flags/flags/ky.svg` },
  { code: "kz", name: "Kazakhstan", url: `https://hatscripts.github.io/circle-flags/flags/kz.svg` },
  { code: "la", name: "Laos", url: `https://hatscripts.github.io/circle-flags/flags/la.svg` },
  { code: "lb", name: "Lebanon", url: `https://hatscripts.github.io/circle-flags/flags/lb.svg` },
  { code: "lc", name: "Saint Lucia", url: `https://hatscripts.github.io/circle-flags/flags/lc.svg` },
  { code: "li", name: "Liechtenstein", url: `https://hatscripts.github.io/circle-flags/flags/li.svg` },
  { code: "lk", name: "Sri Lanka", url: `https://hatscripts.github.io/circle-flags/flags/lk.svg` },
  { code: "lr", name: "Liberia", url: `https://hatscripts.github.io/circle-flags/flags/lr.svg` },
  { code: "ls", name: "Lesotho", url: `https://hatscripts.github.io/circle-flags/flags/ls.svg` },
  { code: "lt", name: "Lithuania", url: `https://hatscripts.github.io/circle-flags/flags/lt.svg` },
  { code: "lu", name: "Luxembourg", url: `https://hatscripts.github.io/circle-flags/flags/lu.svg` },
  { code: "lv", name: "Latvia", url: `https://hatscripts.github.io/circle-flags/flags/lv.svg` },
  { code: "ly", name: "Libya", url: `https://hatscripts.github.io/circle-flags/flags/ly.svg` },
  { code: "ma", name: "Morocco", url: `https://hatscripts.github.io/circle-flags/flags/ma.svg` },
  { code: "mc", name: "Monaco", url: `https://hatscripts.github.io/circle-flags/flags/mc.svg` },
  { code: "md", name: "Moldova", url: `https://hatscripts.github.io/circle-flags/flags/md.svg` },
  { code: "me", name: "Montenegro", url: `https://hatscripts.github.io/circle-flags/flags/me.svg` },
  { code: "mf", name: "Saint-Martin", url: `https://hatscripts.github.io/circle-flags/flags/mf.svg` },
  { code: "mg", name: "Madagascar", url: `https://hatscripts.github.io/circle-flags/flags/mg.svg` },
  { code: "mh", name: "Marshall Islands", url: `https://hatscripts.github.io/circle-flags/flags/mh.svg` },
  { code: "mk", name: "North Macedonia", url: `https://hatscripts.github.io/circle-flags/flags/mk.svg` },
  { code: "ml", name: "Mali", url: `https://hatscripts.github.io/circle-flags/flags/ml.svg` },
  { code: "mm", name: "Myanmar", url: `https://hatscripts.github.io/circle-flags/flags/mm.svg` },
  { code: "mn", name: "Mongolia", url: `https://hatscripts.github.io/circle-flags/flags/mn.svg` },
  { code: "mo", name: "Macao", url: `https://hatscripts.github.io/circle-flags/flags/mo.svg` },
  { code: "mp", name: "Northern Mariana Islands", url: `https://hatscripts.github.io/circle-flags/flags/mp.svg` },
  { code: "mq", name: "Martinique", url: `https://hatscripts.github.io/circle-flags/flags/mq.svg` },
  { code: "mr", name: "Mauritania", url: `https://hatscripts.github.io/circle-flags/flags/mr.svg` },
  { code: "ms", name: "Montserrat", url: `https://hatscripts.github.io/circle-flags/flags/ms.svg` },
  { code: "mt", name: "Malta", url: `https://hatscripts.github.io/circle-flags/flags/mt.svg` },
  { code: "mu", name: "Mauritius", url: `https://hatscripts.github.io/circle-flags/flags/mu.svg` },
  { code: "mv", name: "Maldives", url: `https://hatscripts.github.io/circle-flags/flags/mv.svg` },
  { code: "mw", name: "Malawi", url: `https://hatscripts.github.io/circle-flags/flags/mw.svg` },
  { code: "mx", name: "Mexico", url: `https://hatscripts.github.io/circle-flags/flags/mx.svg` },
  { code: "my", name: "Malaysia", url: `https://hatscripts.github.io/circle-flags/flags/my.svg` },
  { code: "mz", name: "Mozambique", url: `https://hatscripts.github.io/circle-flags/flags/mz.svg` },
  { code: "na", name: "Namibia", url: `https://hatscripts.github.io/circle-flags/flags/na.svg` },
  { code: "nc", name: "New Caledonia", url: `https://hatscripts.github.io/circle-flags/flags/nc.svg` },
  { code: "ne", name: "Niger", url: `https://hatscripts.github.io/circle-flags/flags/ne.svg` },
  { code: "nf", name: "Norfolk Island", url: `https://hatscripts.github.io/circle-flags/flags/nf.svg` },
  { code: "ng", name: "Nigeria", url: `https://hatscripts.github.io/circle-flags/flags/ng.svg` },
  { code: "ni", name: "Nicaragua", url: `https://hatscripts.github.io/circle-flags/flags/ni.svg` },
  { code: "nl", name: "Netherlands", url: `https://hatscripts.github.io/circle-flags/flags/nl.svg` },
  { code: "nl-fr", name: "Friesland", url: `https://hatscripts.github.io/circle-flags/flags/nl-fr.svg` },
  { code: "no", name: "Norway", url: `https://hatscripts.github.io/circle-flags/flags/no.svg` },
  { code: "np", name: "Nepal", url: `https://hatscripts.github.io/circle-flags/flags/np.svg` },
  { code: "nr", name: "Nauru", url: `https://hatscripts.github.io/circle-flags/flags/nr.svg` },
  { code: "nu", name: "Niue", url: `https://hatscripts.github.io/circle-flags/flags/nu.svg` },
  { code: "nz", name: "New Zealand", url: `https://hatscripts.github.io/circle-flags/flags/nz.svg` },
  { code: "om", name: "Oman", url: `https://hatscripts.github.io/circle-flags/flags/om.svg` },
  { code: "pa", name: "Panama", url: `https://hatscripts.github.io/circle-flags/flags/pa.svg` },
  { code: "pe", name: "Peru", url: `https://hatscripts.github.io/circle-flags/flags/pe.svg` },
  { code: "pf", name: "French Polynesia", url: `https://hatscripts.github.io/circle-flags/flags/pf.svg` },
  { code: "pg", name: "Papua New Guinea", url: `https://hatscripts.github.io/circle-flags/flags/pg.svg` },
  { code: "ph", name: "Philippines", url: `https://hatscripts.github.io/circle-flags/flags/ph.svg` },
  { code: "pk", name: "Pakistan", url: `https://hatscripts.github.io/circle-flags/flags/pk.svg` },
  { code: "pk-jk", name: "Azad Kashmir", url: `https://hatscripts.github.io/circle-flags/flags/pk-jk.svg` },
  { code: "pk-sd", name: "Sindh", url: `https://hatscripts.github.io/circle-flags/flags/pk-sd.svg` },
  { code: "pl", name: "Poland", url: `https://hatscripts.github.io/circle-flags/flags/pl.svg` },
  { code: "pm", name: "Saint Pierre and Miquelon", url: `https://hatscripts.github.io/circle-flags/flags/pm.svg` },
  { code: "pn", name: "Pitcairn Islands", url: `https://hatscripts.github.io/circle-flags/flags/pn.svg` },
  { code: "pr", name: "Puerto Rico", url: `https://hatscripts.github.io/circle-flags/flags/pr.svg` },
  { code: "ps", name: "Palestine", url: `https://hatscripts.github.io/circle-flags/flags/ps.svg` },
  { code: "pt", name: "Portugal", url: `https://hatscripts.github.io/circle-flags/flags/pt.svg` },
  { code: "pt-20", name: "Azores", url: `https://hatscripts.github.io/circle-flags/flags/pt-20.svg` },
  { code: "pt-30", name: "Madeira", url: `https://hatscripts.github.io/circle-flags/flags/pt-30.svg` },
  { code: "pw", name: "Palau", url: `https://hatscripts.github.io/circle-flags/flags/pw.svg` },
  { code: "py", name: "Paraguay", url: `https://hatscripts.github.io/circle-flags/flags/py.svg` },
  { code: "qa", name: "Qatar", url: `https://hatscripts.github.io/circle-flags/flags/qa.svg` },
  { code: "re", name: "Réunion", url: `https://hatscripts.github.io/circle-flags/flags/re.svg` },
  { code: "ro", name: "Romania", url: `https://hatscripts.github.io/circle-flags/flags/ro.svg` },
  { code: "rs", name: "Serbia", url: `https://hatscripts.github.io/circle-flags/flags/rs.svg` },
  { code: "ru", name: "Russia", url: `https://hatscripts.github.io/circle-flags/flags/ru.svg` },
  { code: "ru-ba", name: "Bashkortostan", url: `https://hatscripts.github.io/circle-flags/flags/ru-ba.svg` },
  { code: "ru-ce", name: "Chechnya", url: `https://hatscripts.github.io/circle-flags/flags/ru-ce.svg` },
  { code: "ru-cu", name: "Chuvashia", url: `https://hatscripts.github.io/circle-flags/flags/ru-cu.svg` },
  { code: "ru-da", name: "Dagestan", url: `https://hatscripts.github.io/circle-flags/flags/ru-da.svg` },
  { code: "ru-ko", name: "Komi Republic", url: `https://hatscripts.github.io/circle-flags/flags/ru-ko.svg` },
  { code: "ru-ta", name: "Tatarstan", url: `https://hatscripts.github.io/circle-flags/flags/ru-ta.svg` },
  { code: "ru-ud", name: "Udmurtia", url: `https://hatscripts.github.io/circle-flags/flags/ru-ud.svg` },
  { code: "rw", name: "Rwanda", url: `https://hatscripts.github.io/circle-flags/flags/rw.svg` },
  { code: "sa", name: "Saudi Arabia", url: `https://hatscripts.github.io/circle-flags/flags/sa.svg` },
  { code: "sb", name: "Solomon Islands", url: `https://hatscripts.github.io/circle-flags/flags/sb.svg` },
  { code: "sc", name: "Seychelles", url: `https://hatscripts.github.io/circle-flags/flags/sc.svg` },
  { code: "sd", name: "Sudan", url: `https://hatscripts.github.io/circle-flags/flags/sd.svg` },
  { code: "se", name: "Sweden", url: `https://hatscripts.github.io/circle-flags/flags/se.svg` },
  { code: "sg", name: "Singapore", url: `https://hatscripts.github.io/circle-flags/flags/sg.svg` },
  { code: "sh-ac", name: "Ascension Island", url: `https://hatscripts.github.io/circle-flags/flags/sh-ac.svg` },
  { code: "sh-hl", name: "Saint Helena", url: `https://hatscripts.github.io/circle-flags/flags/sh-hl.svg` },
  { code: "sh-ta", name: "Tristan da Cunha", url: `https://hatscripts.github.io/circle-flags/flags/sh-ta.svg` },
  { code: "si", name: "Slovenia", url: `https://hatscripts.github.io/circle-flags/flags/si.svg` },
  { code: "sj", name: "Svalbard and Jan Mayen", url: `https://hatscripts.github.io/circle-flags/flags/sj.svg` },
  { code: "sk", name: "Slovakia", url: `https://hatscripts.github.io/circle-flags/flags/sk.svg` },
  { code: "sl", name: "Sierra Leone", url: `https://hatscripts.github.io/circle-flags/flags/sl.svg` },
  { code: "sm", name: "San Marino", url: `https://hatscripts.github.io/circle-flags/flags/sm.svg` },
  { code: "sn", name: "Senegal", url: `https://hatscripts.github.io/circle-flags/flags/sn.svg` },
  { code: "so", name: "Somalia", url: `https://hatscripts.github.io/circle-flags/flags/so.svg` },
  { code: "sr", name: "Suriname", url: `https://hatscripts.github.io/circle-flags/flags/sr.svg` },
  { code: "ss", name: "South Sudan", url: `https://hatscripts.github.io/circle-flags/flags/ss.svg` },
  { code: "st", name: "São Tomé and Príncipe", url: `https://hatscripts.github.io/circle-flags/flags/st.svg` },
  { code: "sv", name: "El Salvador", url: `https://hatscripts.github.io/circle-flags/flags/sv.svg` },
  { code: "sx", name: "Sint Maarten", url: `https://hatscripts.github.io/circle-flags/flags/sx.svg` },
  { code: "sy", name: "Syria", url: `https://hatscripts.github.io/circle-flags/flags/sy.svg` },
  { code: "sz", name: "Eswatini", url: `https://hatscripts.github.io/circle-flags/flags/sz.svg` },
  { code: "tc", name: "Turks and Caicos Islands", url: `https://hatscripts.github.io/circle-flags/flags/tc.svg` },
  { code: "td", name: "Chad", url: `https://hatscripts.github.io/circle-flags/flags/td.svg` },
  { code: "tf", name: "French Southern Territories", url: `https://hatscripts.github.io/circle-flags/flags/tf.svg` },
  { code: "tg", name: "Togo", url: `https://hatscripts.github.io/circle-flags/flags/tg.svg` },
  { code: "th", name: "Thailand", url: `https://hatscripts.github.io/circle-flags/flags/th.svg` },
  { code: "tj", name: "Tajikistan", url: `https://hatscripts.github.io/circle-flags/flags/tj.svg` },
  { code: "tk", name: "Tokelau", url: `https://hatscripts.github.io/circle-flags/flags/tk.svg` },
  { code: "tl", name: "Timor-Leste", url: `https://hatscripts.github.io/circle-flags/flags/tl.svg` },
  { code: "tm", name: "Turkmenistan", url: `https://hatscripts.github.io/circle-flags/flags/tm.svg` },
  { code: "tn", name: "Tunisia", url: `https://hatscripts.github.io/circle-flags/flags/tn.svg` },
  { code: "to", name: "Tonga", url: `https://hatscripts.github.io/circle-flags/flags/to.svg` },
  { code: "tr", name: "Turkey", url: `https://hatscripts.github.io/circle-flags/flags/tr.svg` },
  { code: "tt", name: "Trinidad and Tobago", url: `https://hatscripts.github.io/circle-flags/flags/tt.svg` },
  { code: "tv", name: "Tuvalu", url: `https://hatscripts.github.io/circle-flags/flags/tv.svg` },
  { code: "tw", name: "Taiwan", url: `https://hatscripts.github.io/circle-flags/flags/tw.svg` },
  { code: "tz", name: "Tanzania", url: `https://hatscripts.github.io/circle-flags/flags/tz.svg` },
  { code: "ua", name: "Ukraine", url: `https://hatscripts.github.io/circle-flags/flags/ua.svg` },
  { code: "ug", name: "Uganda", url: `https://hatscripts.github.io/circle-flags/flags/ug.svg` },
  { code: "us", name: "United States", url: `https://hatscripts.github.io/circle-flags/flags/us.svg` },
  { code: "us-ak", name: "Alaska", url: `https://hatscripts.github.io/circle-flags/flags/us-ak.svg` },
  { code: "us-al", name: "Alabama", url: `https://hatscripts.github.io/circle-flags/flags/us-al.svg` },
  { code: "us-ar", name: "Arkansas", url: `https://hatscripts.github.io/circle-flags/flags/us-ar.svg` },
  { code: "us-az", name: "Arizona", url: `https://hatscripts.github.io/circle-flags/flags/us-az.svg` },
  { code: "us-ca", name: "California", url: `https://hatscripts.github.io/circle-flags/flags/us-ca.svg` },
  { code: "us-co", name: "Colorado", url: `https://hatscripts.github.io/circle-flags/flags/us-co.svg` },
  { code: "us-dc", name: "District of Columbia", url: `https://hatscripts.github.io/circle-flags/flags/us-dc.svg` },
  { code: "us-fl", name: "Florida", url: `https://hatscripts.github.io/circle-flags/flags/us-fl.svg` },
  { code: "us-ga", name: "Georgia", url: `https://hatscripts.github.io/circle-flags/flags/us-ga.svg` },
  { code: "us-hi", name: "Hawaii", url: `https://hatscripts.github.io/circle-flags/flags/us-hi.svg` },
  { code: "us-in", name: "Indiana", url: `https://hatscripts.github.io/circle-flags/flags/us-in.svg` },
  { code: "us-md", name: "Maryland", url: `https://hatscripts.github.io/circle-flags/flags/us-md.svg` },
  { code: "us-mn", name: "Minnesota", url: `https://hatscripts.github.io/circle-flags/flags/us-mn.svg` },
  { code: "us-mo", name: "Missouri", url: `https://hatscripts.github.io/circle-flags/flags/us-mo.svg` },
  { code: "us-ms", name: "Mississippi", url: `https://hatscripts.github.io/circle-flags/flags/us-ms.svg` },
  { code: "us-nc", name: "North Carolina", url: `https://hatscripts.github.io/circle-flags/flags/us-nc.svg` },
  { code: "us-nm", name: "New Mexico", url: `https://hatscripts.github.io/circle-flags/flags/us-nm.svg` },
  { code: "us-or", name: "Oregon", url: `https://hatscripts.github.io/circle-flags/flags/us-or.svg` },
  { code: "us-ri", name: "Rhode Island", url: `https://hatscripts.github.io/circle-flags/flags/us-ri.svg` },
  { code: "us-sc", name: "South Carolina", url: `https://hatscripts.github.io/circle-flags/flags/us-sc.svg` },
  { code: "us-tn", name: "Tennessee", url: `https://hatscripts.github.io/circle-flags/flags/us-tn.svg` },
  { code: "us-tx", name: "Texas", url: `https://hatscripts.github.io/circle-flags/flags/us-tx.svg` },
  { code: "us-wa", name: "Washington", url: `https://hatscripts.github.io/circle-flags/flags/us-wa.svg` },
  { code: "us-wi", name: "Wisconsin", url: `https://hatscripts.github.io/circle-flags/flags/us-wi.svg` },
  { code: "us-wy", name: "Wyoming", url: `https://hatscripts.github.io/circle-flags/flags/us-wy.svg` },
  { code: "um", name: "US Minor Outlying Islands", url: `https://hatscripts.github.io/circle-flags/flags/um.svg` },
  { code: "uy", name: "Uruguay", url: `https://hatscripts.github.io/circle-flags/flags/uy.svg` },
  { code: "uz", name: "Uzbekistan", url: `https://hatscripts.github.io/circle-flags/flags/uz.svg` },
  { code: "va", name: "Vatican", url: `https://hatscripts.github.io/circle-flags/flags/va.svg` },
  { code: "vc", name: "Saint Vincent and the Grenadines", url: `https://hatscripts.github.io/circle-flags/flags/vc.svg` },
  { code: "ve", name: "Venezuela", url: `https://hatscripts.github.io/circle-flags/flags/ve.svg` },
  { code: "vg", name: "British Virgin Islands", url: `https://hatscripts.github.io/circle-flags/flags/vg.svg` },
  { code: "vi", name: "US Virgin Islands", url: `https://hatscripts.github.io/circle-flags/flags/vi.svg` },
  { code: "vn", name: "Vietnam", url: `https://hatscripts.github.io/circle-flags/flags/vn.svg` },
  { code: "vu", name: "Vanuatu", url: `https://hatscripts.github.io/circle-flags/flags/vu.svg` },
  { code: "wf", name: "Wallis and Futuna", url: `https://hatscripts.github.io/circle-flags/flags/wf.svg` },
  { code: "ws", name: "Samoa", url: `https://hatscripts.github.io/circle-flags/flags/ws.svg` },
  { code: "xk", name: "Kosovo", url: `https://hatscripts.github.io/circle-flags/flags/xk.svg` },
  { code: "ye", name: "Yemen", url: `https://hatscripts.github.io/circle-flags/flags/ye.svg` },
  { code: "yt", name: "Mayotte", url: `https://hatscripts.github.io/circle-flags/flags/yt.svg` },
  { code: "yu", name: "Yugoslavia", url: `https://hatscripts.github.io/circle-flags/flags/yu.svg` },
  { code: "za", name: "South Africa", url: `https://hatscripts.github.io/circle-flags/flags/za.svg` },
  { code: "zm", name: "Zambia", url: `https://hatscripts.github.io/circle-flags/flags/zm.svg` },
  { code: "zw", name: "Zimbabwe", url: `https://hatscripts.github.io/circle-flags/flags/zw.svg` },
];

export function getFlagUrl(code) {
  return `https://hatscripts.github.io/circle-flags/flags/${code}.svg`;
}

export function randomFlag() {
  return FLAGS[Math.floor(Math.random() * FLAGS.length)];
}