import { useState } from 'react'
import styles from './SkinSelector.module.css'

const SKINS = [
  { id: 'classic',   label: 'Classic',       peg: '#F5C842', bg: '#0A0A12', btn: '#FF4FA3' },
  { id: 'neon',      label: 'Neon Arcade',   peg: '#00E5FF', bg: '#050508', btn: '#BF5FFF' },
  { id: 'vintage',   label: 'Vintage Japan', peg: '#E8A020', bg: '#1A0F07', btn: '#CC2200' },
  { id: 'gold',      label: 'Gold Luxury',   peg: '#D4AF37', bg: '#050505', btn: '#C9A84C' },
  { id: 'halloween', label: 'Halloween',     peg: '#FF6B00', bg: '#0A0005', btn: '#9B00FF' },
  { id: 'space',     label: 'Space',         peg: '#7B68EE', bg: '#020008', btn: '#4169E1' },
  { id: 'christmas', label: 'Christmas',     peg: '#FFD700', bg: '#020A02', btn: '#CC0000' },
]

const FLAG_SKINS = [
  { id: 'flag-ad',     label: 'Andorra',                            flag: 'ad' },
  { id: 'flag-ae',     label: 'United Arab Emirates',               flag: 'ae' },
  { id: 'flag-af',     label: 'Afghanistan',                        flag: 'af' },
  { id: 'flag-ag',     label: 'Antigua and Barbuda',                flag: 'ag' },
  { id: 'flag-ai',     label: 'Anguilla',                           flag: 'ai' },
  { id: 'flag-al',     label: 'Albania',                            flag: 'al' },
  { id: 'flag-am',     label: 'Armenia',                            flag: 'am' },
  { id: 'flag-an',     label: 'Netherlands Antilles',               flag: 'an' },
  { id: 'flag-ao',     label: 'Angola',                             flag: 'ao' },
  { id: 'flag-aq',     label: 'Antarctica',                         flag: 'aq' },
  { id: 'flag-ar',     label: 'Argentina',                          flag: 'ar' },
  { id: 'flag-as',     label: 'American Samoa',                     flag: 'as' },
  { id: 'flag-at',     label: 'Austria',                            flag: 'at' },
  { id: 'flag-au',     label: 'Australia',                          flag: 'au' },
  { id: 'flag-au-act', label: 'Australian Capital Territory',       flag: 'au-act' },
  { id: 'flag-au-nsw', label: 'New South Wales',                    flag: 'au-nsw' },
  { id: 'flag-au-nt',  label: 'Northern Territory',                 flag: 'au-nt' },
  { id: 'flag-au-qld', label: 'Queensland',                         flag: 'au-qld' },
  { id: 'flag-au-sa',  label: 'South Australia',                    flag: 'au-sa' },
  { id: 'flag-au-tas', label: 'Tasmania',                           flag: 'au-tas' },
  { id: 'flag-au-vic', label: 'Victoria',                           flag: 'au-vic' },
  { id: 'flag-au-wa',  label: 'Western Australia',                  flag: 'au-wa' },
  { id: 'flag-aw',     label: 'Aruba',                              flag: 'aw' },
  { id: 'flag-ax',     label: 'Åland Islands',                      flag: 'ax' },
  { id: 'flag-az',     label: 'Azerbaijan',                         flag: 'az' },
  { id: 'flag-ba',     label: 'Bosnia and Herzegovina',             flag: 'ba' },
  { id: 'flag-bb',     label: 'Barbados',                           flag: 'bb' },
  { id: 'flag-bd',     label: 'Bangladesh',                         flag: 'bd' },
  { id: 'flag-be',     label: 'Belgium',                            flag: 'be' },
  { id: 'flag-bf',     label: 'Burkina Faso',                       flag: 'bf' },
  { id: 'flag-bg',     label: 'Bulgaria',                           flag: 'bg' },
  { id: 'flag-bh',     label: 'Bahrain',                            flag: 'bh' },
  { id: 'flag-bi',     label: 'Burundi',                            flag: 'bi' },
  { id: 'flag-bj',     label: 'Benin',                              flag: 'bj' },
  { id: 'flag-bl',     label: 'Saint Barthélemy',                   flag: 'bl' },
  { id: 'flag-bm',     label: 'Bermuda',                            flag: 'bm' },
  { id: 'flag-bn',     label: 'Brunei',                             flag: 'bn' },
  { id: 'flag-bo',     label: 'Bolivia',                            flag: 'bo' },
  { id: 'flag-bq-bo',  label: 'Bonaire',                            flag: 'bq-bo' },
  { id: 'flag-bq-sa',  label: 'Saba',                               flag: 'bq-sa' },
  { id: 'flag-bq-se',  label: 'Sint Eustatius',                     flag: 'bq-se' },
  { id: 'flag-br',     label: 'Brazil',                             flag: 'br' },
  { id: 'flag-bs',     label: 'Bahamas',                            flag: 'bs' },
  { id: 'flag-bt',     label: 'Bhutan',                             flag: 'bt' },
  { id: 'flag-bv',     label: 'Bouvet Island',                      flag: 'bv' },
  { id: 'flag-bw',     label: 'Botswana',                           flag: 'bw' },
  { id: 'flag-by',     label: 'Belarus',                            flag: 'by' },
  { id: 'flag-bz',     label: 'Belize',                             flag: 'bz' },
  { id: 'flag-ca',     label: 'Canada',                             flag: 'ca' },
  { id: 'flag-ca-bc',  label: 'British Columbia',                   flag: 'ca-bc' },
  { id: 'flag-ca-qc',  label: 'Quebec',                             flag: 'ca-qc' },
  { id: 'flag-cc',     label: 'Cocos (Keeling) Islands',            flag: 'cc' },
  { id: 'flag-cd',     label: 'Congo, DR',                          flag: 'cd' },
  { id: 'flag-cf',     label: 'Central African Republic',           flag: 'cf' },
  { id: 'flag-cg',     label: 'Congo',                              flag: 'cg' },
  { id: 'flag-ch',     label: 'Switzerland',                        flag: 'ch' },
  { id: 'flag-ch-gr',  label: 'Grisons',                            flag: 'ch-gr' },
  { id: 'flag-ci',     label: 'Ivory Coast',                        flag: 'ci' },
  { id: 'flag-ck',     label: 'Cook Islands',                       flag: 'ck' },
  { id: 'flag-cl',     label: 'Chile',                              flag: 'cl' },
  { id: 'flag-cm',     label: 'Cameroon',                           flag: 'cm' },
  { id: 'flag-cn',     label: 'China',                              flag: 'cn' },
  { id: 'flag-cn-xj',  label: 'Xinjiang',                           flag: 'cn-xj' },
  { id: 'flag-cn-xz',  label: 'Tibet',                              flag: 'cn-xz' },
  { id: 'flag-co',     label: 'Colombia',                           flag: 'co' },
  { id: 'flag-cq',     label: 'Sark',                               flag: 'cq' },
  { id: 'flag-cr',     label: 'Costa Rica',                         flag: 'cr' },
  { id: 'flag-cu',     label: 'Cuba',                               flag: 'cu' },
  { id: 'flag-cv',     label: 'Cabo Verde',                         flag: 'cv' },
  { id: 'flag-cw',     label: 'Curaçao',                            flag: 'cw' },
  { id: 'flag-cx',     label: 'Christmas Island',                   flag: 'cx' },
  { id: 'flag-cy',     label: 'Cyprus',                             flag: 'cy' },
  { id: 'flag-cz',     label: 'Czechia',                            flag: 'cz' },
  { id: 'flag-de',     label: 'Germany',                            flag: 'de' },
  { id: 'flag-dj',     label: 'Djibouti',                           flag: 'dj' },
  { id: 'flag-dk',     label: 'Denmark',                            flag: 'dk' },
  { id: 'flag-dm',     label: 'Dominica',                           flag: 'dm' },
  { id: 'flag-do',     label: 'Dominican Republic',                 flag: 'do' },
  { id: 'flag-dz',     label: 'Algeria',                            flag: 'dz' },
  { id: 'flag-ec',     label: 'Ecuador',                            flag: 'ec' },
  { id: 'flag-ec-w',   label: 'Galápagos',                          flag: 'ec-w' },
  { id: 'flag-ee',     label: 'Estonia',                            flag: 'ee' },
  { id: 'flag-eg',     label: 'Egypt',                              flag: 'eg' },
  { id: 'flag-eh',     label: 'Western Sahara',                     flag: 'eh' },
  { id: 'flag-er',     label: 'Eritrea',                            flag: 'er' },
  { id: 'flag-es',     label: 'Spain',                              flag: 'es' },
  { id: 'flag-es-ar',  label: 'Aragon',                             flag: 'es-ar' },
  { id: 'flag-es-ce',  label: 'Ceuta',                              flag: 'es-ce' },
  { id: 'flag-es-cn',  label: 'Canary Islands',                     flag: 'es-cn' },
  { id: 'flag-es-ct',  label: 'Catalonia',                          flag: 'es-ct' },
  { id: 'flag-es-ga',  label: 'Galicia',                            flag: 'es-ga' },
  { id: 'flag-es-ib',  label: 'Balearic Islands',                   flag: 'es-ib' },
  { id: 'flag-es-ml',  label: 'Melilla',                            flag: 'es-ml' },
  { id: 'flag-es-pv',  label: 'Basque Country',                     flag: 'es-pv' },
  { id: 'flag-es-vc',  label: 'Valencia',                           flag: 'es-vc' },
  { id: 'flag-et',     label: 'Ethiopia',                           flag: 'et' },
  { id: 'flag-et-af',  label: 'Afar',                               flag: 'et-af' },
  { id: 'flag-et-am',  label: 'Amhara',                             flag: 'et-am' },
  { id: 'flag-et-be',  label: 'Benishangul-Gumuz',                  flag: 'et-be' },
  { id: 'flag-et-ga',  label: 'Gambela',                            flag: 'et-ga' },
  { id: 'flag-et-ha',  label: 'Harari',                             flag: 'et-ha' },
  { id: 'flag-et-or',  label: 'Oromia',                             flag: 'et-or' },
  { id: 'flag-et-si',  label: 'Sidama',                             flag: 'et-si' },
  { id: 'flag-et-sn',  label: 'Southern Nations',                   flag: 'et-sn' },
  { id: 'flag-et-so',  label: 'Somali',                             flag: 'et-so' },
  { id: 'flag-et-sw',  label: 'South West Region',                  flag: 'et-sw' },
  { id: 'flag-et-ti',  label: 'Tigray',                             flag: 'et-ti' },
  { id: 'flag-eu',     label: 'European Union',                     flag: 'eu' },
  { id: 'flag-fi',     label: 'Finland',                            flag: 'fi' },
  { id: 'flag-fj',     label: 'Fiji',                               flag: 'fj' },
  { id: 'flag-fk',     label: 'Falkland Islands',                   flag: 'fk' },
  { id: 'flag-fm',     label: 'Micronesia',                         flag: 'fm' },
  { id: 'flag-fo',     label: 'Faroe Islands',                      flag: 'fo' },
  { id: 'flag-fr',     label: 'France',                             flag: 'fr' },
  { id: 'flag-fr-20r', label: 'Corsica',                            flag: 'fr-20r' },
  { id: 'flag-fr-bre', label: 'Brittany',                           flag: 'fr-bre' },
  { id: 'flag-fr-cp',  label: 'Clipperton Island',                  flag: 'fr-cp' },
  { id: 'flag-ga',     label: 'Gabon',                              flag: 'ga' },
  { id: 'flag-gb',     label: 'United Kingdom',                     flag: 'gb' },
  { id: 'flag-gb-con', label: 'Cornwall',                           flag: 'gb-con' },
  { id: 'flag-gb-eng', label: 'England',                            flag: 'gb-eng' },
  { id: 'flag-gb-nir', label: 'Northern Ireland',                   flag: 'gb-nir' },
  { id: 'flag-gb-ork', label: 'Orkney',                             flag: 'gb-ork' },
  { id: 'flag-gb-sct', label: 'Scotland',                           flag: 'gb-sct' },
  { id: 'flag-gb-wls', label: 'Wales',                              flag: 'gb-wls' },
  { id: 'flag-gd',     label: 'Grenada',                            flag: 'gd' },
  { id: 'flag-ge',     label: 'Georgia',                            flag: 'ge' },
  { id: 'flag-ge-ab',  label: 'Abkhazia',                           flag: 'ge-ab' },
  { id: 'flag-gf',     label: 'French Guiana',                      flag: 'gf' },
  { id: 'flag-gg',     label: 'Guernsey',                           flag: 'gg' },
  { id: 'flag-gh',     label: 'Ghana',                              flag: 'gh' },
  { id: 'flag-gi',     label: 'Gibraltar',                          flag: 'gi' },
  { id: 'flag-gl',     label: 'Greenland',                          flag: 'gl' },
  { id: 'flag-gm',     label: 'Gambia',                             flag: 'gm' },
  { id: 'flag-gn',     label: 'Guinea',                             flag: 'gn' },
  { id: 'flag-gp',     label: 'Guadeloupe',                         flag: 'gp' },
  { id: 'flag-gq',     label: 'Equatorial Guinea',                  flag: 'gq' },
  { id: 'flag-gr',     label: 'Greece',                             flag: 'gr' },
  { id: 'flag-gs',     label: 'South Georgia and South Sandwich Islands', flag: 'gs' },
  { id: 'flag-gt',     label: 'Guatemala',                          flag: 'gt' },
  { id: 'flag-gu',     label: 'Guam',                               flag: 'gu' },
  { id: 'flag-gw',     label: 'Guinea-Bissau',                      flag: 'gw' },
  { id: 'flag-gy',     label: 'Guyana',                             flag: 'gy' },
  { id: 'flag-hk',     label: 'Hong Kong',                          flag: 'hk' },
  { id: 'flag-hm',     label: 'Heard Island and McDonald Islands',  flag: 'hm' },
  { id: 'flag-hn',     label: 'Honduras',                           flag: 'hn' },
  { id: 'flag-hr',     label: 'Croatia',                            flag: 'hr' },
  { id: 'flag-ht',     label: 'Haiti',                              flag: 'ht' },
  { id: 'flag-hu',     label: 'Hungary',                            flag: 'hu' },
  { id: 'flag-id',     label: 'Indonesia',                          flag: 'id' },
  { id: 'flag-id-jb',  label: 'West Java',                          flag: 'id-jb' },
  { id: 'flag-id-jt',  label: 'Central Java',                       flag: 'id-jt' },
  { id: 'flag-ie',     label: 'Ireland',                            flag: 'ie' },
  { id: 'flag-il',     label: 'Israel',                             flag: 'il' },
  { id: 'flag-im',     label: 'Isle of Man',                        flag: 'im' },
  { id: 'flag-in',     label: 'India',                              flag: 'in' },
  { id: 'flag-in-as',  label: 'Assam',                              flag: 'in-as' },
  { id: 'flag-in-gj',  label: 'Gujarat',                            flag: 'in-gj' },
  { id: 'flag-in-ka',  label: 'Karnataka',                          flag: 'in-ka' },
  { id: 'flag-in-mn',  label: 'Manipur',                            flag: 'in-mn' },
  { id: 'flag-in-mz',  label: 'Mizoram',                            flag: 'in-mz' },
  { id: 'flag-in-or',  label: 'Odisha',                             flag: 'in-or' },
  { id: 'flag-in-tg',  label: 'Telangana',                          flag: 'in-tg' },
  { id: 'flag-in-tn',  label: 'Tamil Nadu',                         flag: 'in-tn' },
  { id: 'flag-io',     label: 'British Indian Ocean Territory',     flag: 'io' },
  { id: 'flag-iq',     label: 'Iraq',                               flag: 'iq' },
  { id: 'flag-iq-kr',  label: 'Kurdistan',                          flag: 'iq-kr' },
  { id: 'flag-ir',     label: 'Iran',                               flag: 'ir' },
  { id: 'flag-is',     label: 'Iceland',                            flag: 'is' },
  { id: 'flag-it',     label: 'Italy',                              flag: 'it' },
  { id: 'flag-it-21',  label: 'Piedmont',                           flag: 'it-21' },
  { id: 'flag-it-23',  label: 'Aosta Valley',                       flag: 'it-23' },
  { id: 'flag-it-25',  label: 'Lombardy',                           flag: 'it-25' },
  { id: 'flag-it-32',  label: 'Trentino-Alto Adige',                flag: 'it-32' },
  { id: 'flag-it-34',  label: 'Veneto',                             flag: 'it-34' },
  { id: 'flag-it-36',  label: 'Friuli Venezia Giulia',              flag: 'it-36' },
  { id: 'flag-it-42',  label: 'Liguria',                            flag: 'it-42' },
  { id: 'flag-it-45',  label: 'Emilia-Romagna',                     flag: 'it-45' },
  { id: 'flag-it-52',  label: 'Tuscany',                            flag: 'it-52' },
  { id: 'flag-it-55',  label: 'Umbria',                             flag: 'it-55' },
  { id: 'flag-it-57',  label: 'Marche',                             flag: 'it-57' },
  { id: 'flag-it-62',  label: 'Lazio',                              flag: 'it-62' },
  { id: 'flag-it-65',  label: 'Abruzzo',                            flag: 'it-65' },
  { id: 'flag-it-67',  label: 'Molise',                             flag: 'it-67' },
  { id: 'flag-it-72',  label: 'Campania',                           flag: 'it-72' },
  { id: 'flag-it-75',  label: 'Apulia',                             flag: 'it-75' },
  { id: 'flag-it-77',  label: 'Basilicata',                         flag: 'it-77' },
  { id: 'flag-it-78',  label: 'Calabria',                           flag: 'it-78' },
  { id: 'flag-it-82',  label: 'Sicily',                             flag: 'it-82' },
  { id: 'flag-it-88',  label: 'Sardinia',                           flag: 'it-88' },
  { id: 'flag-je',     label: 'Jersey',                             flag: 'je' },
  { id: 'flag-jm',     label: 'Jamaica',                            flag: 'jm' },
  { id: 'flag-jo',     label: 'Jordan',                             flag: 'jo' },
  { id: 'flag-jp',     label: 'Japan',                              flag: 'jp' },
  { id: 'flag-ke',     label: 'Kenya',                              flag: 'ke' },
  { id: 'flag-kg',     label: 'Kyrgyzstan',                         flag: 'kg' },
  { id: 'flag-kh',     label: 'Cambodia',                           flag: 'kh' },
  { id: 'flag-ki',     label: 'Kiribati',                           flag: 'ki' },
  { id: 'flag-km',     label: 'Comoros',                            flag: 'km' },
  { id: 'flag-kn',     label: 'Saint Kitts and Nevis',              flag: 'kn' },
  { id: 'flag-kp',     label: 'North Korea',                        flag: 'kp' },
  { id: 'flag-kr',     label: 'South Korea',                        flag: 'kr' },
  { id: 'flag-kw',     label: 'Kuwait',                             flag: 'kw' },
  { id: 'flag-ky',     label: 'Cayman Islands',                     flag: 'ky' },
  { id: 'flag-kz',     label: 'Kazakhstan',                         flag: 'kz' },
  { id: 'flag-la',     label: 'Laos',                               flag: 'la' },
  { id: 'flag-lb',     label: 'Lebanon',                            flag: 'lb' },
  { id: 'flag-lc',     label: 'Saint Lucia',                        flag: 'lc' },
  { id: 'flag-li',     label: 'Liechtenstein',                      flag: 'li' },
  { id: 'flag-lk',     label: 'Sri Lanka',                          flag: 'lk' },
  { id: 'flag-lr',     label: 'Liberia',                            flag: 'lr' },
  { id: 'flag-ls',     label: 'Lesotho',                            flag: 'ls' },
  { id: 'flag-lt',     label: 'Lithuania',                          flag: 'lt' },
  { id: 'flag-lu',     label: 'Luxembourg',                         flag: 'lu' },
  { id: 'flag-lv',     label: 'Latvia',                             flag: 'lv' },
  { id: 'flag-ly',     label: 'Libya',                              flag: 'ly' },
  { id: 'flag-ma',     label: 'Morocco',                            flag: 'ma' },
  { id: 'flag-mc',     label: 'Monaco',                             flag: 'mc' },
  { id: 'flag-md',     label: 'Moldova',                            flag: 'md' },
  { id: 'flag-me',     label: 'Montenegro',                         flag: 'me' },
  { id: 'flag-mf',     label: 'Saint-Martin',                       flag: 'mf' },
  { id: 'flag-mg',     label: 'Madagascar',                         flag: 'mg' },
  { id: 'flag-mh',     label: 'Marshall Islands',                   flag: 'mh' },
  { id: 'flag-mk',     label: 'North Macedonia',                    flag: 'mk' },
  { id: 'flag-ml',     label: 'Mali',                               flag: 'ml' },
  { id: 'flag-mm',     label: 'Myanmar',                            flag: 'mm' },
  { id: 'flag-mn',     label: 'Mongolia',                           flag: 'mn' },
  { id: 'flag-mo',     label: 'Macao',                              flag: 'mo' },
  { id: 'flag-mp',     label: 'Northern Mariana Islands',           flag: 'mp' },
  { id: 'flag-mq',     label: 'Martinique',                         flag: 'mq' },
  { id: 'flag-mr',     label: 'Mauritania',                         flag: 'mr' },
  { id: 'flag-ms',     label: 'Montserrat',                         flag: 'ms' },
  { id: 'flag-mt',     label: 'Malta',                              flag: 'mt' },
  { id: 'flag-mu',     label: 'Mauritius',                          flag: 'mu' },
  { id: 'flag-mv',     label: 'Maldives',                           flag: 'mv' },
  { id: 'flag-mw',     label: 'Malawi',                             flag: 'mw' },
  { id: 'flag-mx',     label: 'Mexico',                             flag: 'mx' },
  { id: 'flag-my',     label: 'Malaysia',                           flag: 'my' },
  { id: 'flag-mz',     label: 'Mozambique',                         flag: 'mz' },
  { id: 'flag-na',     label: 'Namibia',                            flag: 'na' },
  { id: 'flag-nc',     label: 'New Caledonia',                      flag: 'nc' },
  { id: 'flag-ne',     label: 'Niger',                              flag: 'ne' },
  { id: 'flag-nf',     label: 'Norfolk Island',                     flag: 'nf' },
  { id: 'flag-ng',     label: 'Nigeria',                            flag: 'ng' },
  { id: 'flag-ni',     label: 'Nicaragua',                          flag: 'ni' },
  { id: 'flag-nl',     label: 'Netherlands',                        flag: 'nl' },
  { id: 'flag-nl-fr',  label: 'Friesland',                          flag: 'nl-fr' },
  { id: 'flag-no',     label: 'Norway',                             flag: 'no' },
  { id: 'flag-np',     label: 'Nepal',                              flag: 'np' },
  { id: 'flag-nr',     label: 'Nauru',                              flag: 'nr' },
  { id: 'flag-nu',     label: 'Niue',                               flag: 'nu' },
  { id: 'flag-nz',     label: 'New Zealand',                        flag: 'nz' },
  { id: 'flag-om',     label: 'Oman',                               flag: 'om' },
  { id: 'flag-pa',     label: 'Panama',                             flag: 'pa' },
  { id: 'flag-pe',     label: 'Peru',                               flag: 'pe' },
  { id: 'flag-pf',     label: 'French Polynesia',                   flag: 'pf' },
  { id: 'flag-pg',     label: 'Papua New Guinea',                   flag: 'pg' },
  { id: 'flag-ph',     label: 'Philippines',                        flag: 'ph' },
  { id: 'flag-pk',     label: 'Pakistan',                           flag: 'pk' },
  { id: 'flag-pk-jk',  label: 'Azad Kashmir',                       flag: 'pk-jk' },
  { id: 'flag-pk-sd',  label: 'Sindh',                              flag: 'pk-sd' },
  { id: 'flag-pl',     label: 'Poland',                             flag: 'pl' },
  { id: 'flag-pm',     label: 'Saint Pierre and Miquelon',          flag: 'pm' },
  { id: 'flag-pn',     label: 'Pitcairn Islands',                   flag: 'pn' },
  { id: 'flag-pr',     label: 'Puerto Rico',                        flag: 'pr' },
  { id: 'flag-ps',     label: 'Palestine',                          flag: 'ps' },
  { id: 'flag-pt',     label: 'Portugal',                           flag: 'pt' },
  { id: 'flag-pt-20',  label: 'Azores',                             flag: 'pt-20' },
  { id: 'flag-pt-30',  label: 'Madeira',                            flag: 'pt-30' },
  { id: 'flag-pw',     label: 'Palau',                              flag: 'pw' },
  { id: 'flag-py',     label: 'Paraguay',                           flag: 'py' },
  { id: 'flag-qa',     label: 'Qatar',                              flag: 'qa' },
  { id: 'flag-re',     label: 'Réunion',                            flag: 're' },
  { id: 'flag-ro',     label: 'Romania',                            flag: 'ro' },
  { id: 'flag-rs',     label: 'Serbia',                             flag: 'rs' },
  { id: 'flag-ru',     label: 'Russia',                             flag: 'ru' },
  { id: 'flag-ru-ba',  label: 'Bashkortostan',                      flag: 'ru-ba' },
  { id: 'flag-ru-ce',  label: 'Chechnya',                           flag: 'ru-ce' },
  { id: 'flag-ru-cu',  label: 'Chuvashia',                          flag: 'ru-cu' },
  { id: 'flag-ru-da',  label: 'Dagestan',                           flag: 'ru-da' },
  { id: 'flag-ru-ko',  label: 'Komi Republic',                      flag: 'ru-ko' },
  { id: 'flag-ru-ta',  label: 'Tatarstan',                          flag: 'ru-ta' },
  { id: 'flag-ru-ud',  label: 'Udmurtia',                           flag: 'ru-ud' },
  { id: 'flag-rw',     label: 'Rwanda',                             flag: 'rw' },
  { id: 'flag-sa',     label: 'Saudi Arabia',                       flag: 'sa' },
  { id: 'flag-sb',     label: 'Solomon Islands',                    flag: 'sb' },
  { id: 'flag-sc',     label: 'Seychelles',                         flag: 'sc' },
  { id: 'flag-sd',     label: 'Sudan',                              flag: 'sd' },
  { id: 'flag-se',     label: 'Sweden',                             flag: 'se' },
  { id: 'flag-sg',     label: 'Singapore',                          flag: 'sg' },
  { id: 'flag-sh-ac',  label: 'Ascension Island',                   flag: 'sh-ac' },
  { id: 'flag-sh-hl',  label: 'Saint Helena',                       flag: 'sh-hl' },
  { id: 'flag-sh-ta',  label: 'Tristan da Cunha',                   flag: 'sh-ta' },
  { id: 'flag-si',     label: 'Slovenia',                           flag: 'si' },
  { id: 'flag-sj',     label: 'Svalbard and Jan Mayen',             flag: 'sj' },
  { id: 'flag-sk',     label: 'Slovakia',                           flag: 'sk' },
  { id: 'flag-sl',     label: 'Sierra Leone',                       flag: 'sl' },
  { id: 'flag-sm',     label: 'San Marino',                         flag: 'sm' },
  { id: 'flag-sn',     label: 'Senegal',                            flag: 'sn' },
  { id: 'flag-so',     label: 'Somalia',                            flag: 'so' },
  { id: 'flag-sr',     label: 'Suriname',                           flag: 'sr' },
  { id: 'flag-ss',     label: 'South Sudan',                        flag: 'ss' },
  { id: 'flag-st',     label: 'São Tomé and Príncipe',              flag: 'st' },
  { id: 'flag-sv',     label: 'El Salvador',                        flag: 'sv' },
  { id: 'flag-sx',     label: 'Sint Maarten',                       flag: 'sx' },
  { id: 'flag-sy',     label: 'Syria',                              flag: 'sy' },
  { id: 'flag-sz',     label: 'Eswatini',                           flag: 'sz' },
  { id: 'flag-tc',     label: 'Turks and Caicos Islands',           flag: 'tc' },
  { id: 'flag-td',     label: 'Chad',                               flag: 'td' },
  { id: 'flag-tf',     label: 'French Southern Territories',        flag: 'tf' },
  { id: 'flag-tg',     label: 'Togo',                               flag: 'tg' },
  { id: 'flag-th',     label: 'Thailand',                           flag: 'th' },
  { id: 'flag-tj',     label: 'Tajikistan',                         flag: 'tj' },
  { id: 'flag-tk',     label: 'Tokelau',                            flag: 'tk' },
  { id: 'flag-tl',     label: 'Timor-Leste',                        flag: 'tl' },
  { id: 'flag-tm',     label: 'Turkmenistan',                       flag: 'tm' },
  { id: 'flag-tn',     label: 'Tunisia',                            flag: 'tn' },
  { id: 'flag-to',     label: 'Tonga',                              flag: 'to' },
  { id: 'flag-tr',     label: 'Turkey',                             flag: 'tr' },
  { id: 'flag-tt',     label: 'Trinidad and Tobago',                flag: 'tt' },
  { id: 'flag-tv',     label: 'Tuvalu',                             flag: 'tv' },
  { id: 'flag-tw',     label: 'Taiwan',                             flag: 'tw' },
  { id: 'flag-tz',     label: 'Tanzania',                           flag: 'tz' },
  { id: 'flag-ua',     label: 'Ukraine',                            flag: 'ua' },
  { id: 'flag-ug',     label: 'Uganda',                             flag: 'ug' },
  { id: 'flag-um',     label: 'US Minor Outlying Islands',          flag: 'um' },
  { id: 'flag-us',     label: 'United States',                      flag: 'us' },
  { id: 'flag-us-ak',  label: 'Alaska',                             flag: 'us-ak' },
  { id: 'flag-us-al',  label: 'Alabama',                            flag: 'us-al' },
  { id: 'flag-us-ar',  label: 'Arkansas',                           flag: 'us-ar' },
  { id: 'flag-us-az',  label: 'Arizona',                            flag: 'us-az' },
  { id: 'flag-us-ca',  label: 'California',                         flag: 'us-ca' },
  { id: 'flag-us-co',  label: 'Colorado',                           flag: 'us-co' },
  { id: 'flag-us-dc',  label: 'District of Columbia',               flag: 'us-dc' },
  { id: 'flag-us-fl',  label: 'Florida',                            flag: 'us-fl' },
  { id: 'flag-us-ga',  label: 'Georgia (US)',                       flag: 'us-ga' },
  { id: 'flag-us-hi',  label: 'Hawaii',                             flag: 'us-hi' },
  { id: 'flag-us-in',  label: 'Indiana',                            flag: 'us-in' },
  { id: 'flag-us-md',  label: 'Maryland',                           flag: 'us-md' },
  { id: 'flag-us-mn',  label: 'Minnesota',                          flag: 'us-mn' },
  { id: 'flag-us-mo',  label: 'Missouri',                           flag: 'us-mo' },
  { id: 'flag-us-ms',  label: 'Mississippi',                        flag: 'us-ms' },
  { id: 'flag-us-nc',  label: 'North Carolina',                     flag: 'us-nc' },
  { id: 'flag-us-nm',  label: 'New Mexico',                         flag: 'us-nm' },
  { id: 'flag-us-or',  label: 'Oregon',                             flag: 'us-or' },
  { id: 'flag-us-ri',  label: 'Rhode Island',                       flag: 'us-ri' },
  { id: 'flag-us-sc',  label: 'South Carolina',                     flag: 'us-sc' },
  { id: 'flag-us-tn',  label: 'Tennessee',                          flag: 'us-tn' },
  { id: 'flag-us-tx',  label: 'Texas',                              flag: 'us-tx' },
  { id: 'flag-us-wa',  label: 'Washington (State)',                  flag: 'us-wa' },
  { id: 'flag-us-wi',  label: 'Wisconsin',                          flag: 'us-wi' },
  { id: 'flag-us-wy',  label: 'Wyoming',                            flag: 'us-wy' },
  { id: 'flag-uy',     label: 'Uruguay',                            flag: 'uy' },
  { id: 'flag-uz',     label: 'Uzbekistan',                         flag: 'uz' },
  { id: 'flag-va',     label: 'Holy See (Vatican)',                  flag: 'va' },
  { id: 'flag-vc',     label: 'Saint Vincent and the Grenadines',   flag: 'vc' },
  { id: 'flag-ve',     label: 'Venezuela',                          flag: 've' },
  { id: 'flag-vg',     label: 'Virgin Islands (British)',            flag: 'vg' },
  { id: 'flag-vi',     label: 'Virgin Islands (U.S.)',               flag: 'vi' },
  { id: 'flag-vn',     label: 'Vietnam',                            flag: 'vn' },
  { id: 'flag-vu',     label: 'Vanuatu',                            flag: 'vu' },
  { id: 'flag-wf',     label: 'Wallis and Futuna',                  flag: 'wf' },
  { id: 'flag-ws',     label: 'Samoa',                              flag: 'ws' },
  { id: 'flag-xk',     label: 'Kosovo',                             flag: 'xk' },
  { id: 'flag-ye',     label: 'Yemen',                              flag: 'ye' },
  { id: 'flag-yt',     label: 'Mayotte',                            flag: 'yt' },
  { id: 'flag-yu',     label: 'Yugoslavia',                         flag: 'yu' },
  { id: 'flag-za',     label: 'South Africa',                       flag: 'za' },
  { id: 'flag-zm',     label: 'Zambia',                             flag: 'zm' },
  { id: 'flag-zw',     label: 'Zimbabwe',                           flag: 'zw' },
]

const ALL_SKINS = [...SKINS, ...FLAG_SKINS]

export default function SkinSelector({ currentSkin, onChange }) {
  const [open, setOpen] = useState(false)
  const current = ALL_SKINS.find(s => s.id === currentSkin) || SKINS[0]

  return (
    <div className={styles.wrapper}>
      <button
        className={styles.trigger}
        onClick={() => setOpen(v => !v)}
        title="Change theme"
      >
        <SkinSwatch skin={current} size={20} />
        <span>{current.label}</span>
        <span className={styles.arrow}>{open ? '▲' : '▼'}</span>
      </button>

      {open && (
        <div className={styles.dropdown}>
          {SKINS.map(skin => (
            <button
              key={skin.id}
              className={`${styles.option} ${skin.id === currentSkin ? styles.selected : ''}`}
              onClick={() => { onChange(skin.id); setOpen(false) }}
            >
              <SkinSwatch skin={skin} size={28} />
              <span>{skin.label}</span>
              {skin.id === currentSkin && <span className={styles.check}>✓</span>}
            </button>
          ))}

          <div className={styles.divider}>Flags</div>

          {FLAG_SKINS.map(skin => (
            <button
              key={skin.id}
              className={`${styles.option} ${skin.id === currentSkin ? styles.selected : ''}`}
              onClick={() => { onChange(skin.id); setOpen(false) }}
            >
              <SkinSwatch skin={skin} size={28} />
              <span>{skin.label}</span>
              {skin.id === currentSkin && <span className={styles.check}>✓</span>}
            </button>
          ))}
        </div>
      )}
    </div>
  )
}

function SkinSwatch({ skin, size }) {
  if (skin.flag) {
    return (
      <img
        src={`https://hatscripts.github.io/circle-flags/flags/${skin.flag}.svg`}
        width={size}
        height={size}
        alt={skin.label}
        style={{
          borderRadius: '50%',
          border: '1.5px solid rgba(255,255,255,0.15)',
          flexShrink: 0,
        }}
      />
    )
  }

  return (
    <div
      style={{
        width: size,
        height: size,
        borderRadius: '50%',
        background: `radial-gradient(circle at 60% 40%, ${skin.peg} 0 30%, ${skin.btn} 30% 65%, ${skin.bg} 65%)`,
        border: '1.5px solid rgba(255,255,255,0.15)',
        flexShrink: 0,
      }}
    />
  )
}
